# Site settings
title: Johannes Haupt
description: > # this means to ignore newlines until "baseurl:"
  Exploring data science and machine learning one step at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/johaupt/johaupt.github.io" # the base hostname & protocol for your site
github_username:  johaupt
twitter_username: captn_head

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-100815065-1
